Get fee recipient for StakeHouse
dappnode/StakingBrain pull request #216
Opened 2023-04-13 14:08 UTC by dsimog01

Fee recipient is automatically calculated for StakeHouse

2023-04-27 13:39 UTC, dsimog01 commented
![image](https://user-images.githubusercontent.com/47595345/234879901-7bada120-5c9c-4839-9190-01c21713df69.png)

2023-04-28 08:39 UTC, pablomendezroyo requested changes

2023-04-28 08:39 UTC, pablomendezroyo commented on packages/brain/package.json
> +    "ethers": "^5.7.0",
why are you installing another extra dependency?

2023-04-28 08:42 UTC, dsimog01 commented on packages/brain/src/modules/stakingProtocols/stakehouse/index.ts
> +import { getDefaultProvider } from "ethers";
`ethers` is used here @pablomendezroyo

2023-04-28 08:44 UTC, pablomendezroyo approved these changes

2023-04-28 09:20 UTC, merged